Execute : memoObject calendarObject mainObject
	gcc -o ExecuteDaily memo.o calendar.o main.o # Need ‘Tab’ Key
memoObject :
	gcc -c -o memo.o memo.c # Need ‘Tab’ Key
calendarObject :
	gcc -c -o calendar.o calendar.c # Need ‘Tab’ Key
mainObject : main.c
	gcc -c -o main.o main.c # Need ‘Tab’ Key
clean :
	rm *.o ExecuteDaily